name: 1 - Hello World GitHub actions

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 15 * * *'
  # push: # git push
  #   branches:
  #     - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "hello"