name: 1 - Hello World GitHub actions

on:
  workflow_dispatch:
  push: # git push
    branch:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "hello"